### PR TITLE
Direct method

### PR DESCRIPTION
**Pull request by alexwdong**
First implementation of direct method. Depends on LoggingPolicy specified in @mihamerstan's branch #11.

I have no preference on how to organize functions/classes, but this depends on the Bandit class and also the LoggingPolicy class. In particular it depends on a (trained) policy contained in the Bandit class, which sounds weird to me, at least after doing Hw3 for ML tools.

### CODE REVIEW

**Comment by guidopetri** [comment]
@alexwdong can you put this in a .py file and run the evaluation for the logging policy that michael has in the ipynb?

**Comment by mihamerstan** [comment]
I changed the LoggingPolicy class and replaced `get_pa_x` with `predict_proba`. So you'll have to update those few lines in the notebook. Apologies for the breaking changes.

**Comment by alexwdong** [comment]
@mihamerstan's changes look good. I moved the main functions into `evaluation.py`. I also updated logging_policy.py to be the version from logging_test branch. I think this branch is ready to merge

**Comment by mihamerstan** [comment]
Tested in the notebook, looks good! Merging.

**Pull request merged**
